name: Publish NuGet

on:
  workflow_run:
    workflows: [ "Build && Tests" ]
    types:
      - completed

jobs:
  publish:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./LiteTUI
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release 

      - name: Pack
        run: dotnet pack --configuration Release --no-build -o ./nupkg

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json